ETHEREUM_JSONRPC_HTTP_URL=http://mantra-canary-net-1-ae2-archive-rpc.mantra-canary-net-1.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox:8545
ETHEREUM_JSONRPC_FALLBACK_HTTP_URL=https://evm.canary.mantrachain.dev
ETHEREUM_JSONRPC_TRACE_URL=http://mantra-canary-net-1-ae2-archive-rpc.mantra-canary-net-1.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox:8545
ETHEREUM_JSONRPC_FALLBACK_TRACE_URL=https://evm.canary.mantrachain.dev
ETHEREUM_JSONRPC_WS_URL=ws://mantra-canary-net-1-ae2-archive-rpc.mantra-canary-net-1.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox:8546
ETHEREUM_JSONRPC_FALLBACK_WS_URL=ws://evm.canary.mantrachain.dev/ws
NETWORK=CANARY
BLOCKSCOUT_HOST=blockscout.canary.mantrachain.dev
BLOCKSCOUT_PROTOCOL=https
PGHOST=blockscout-canary-postgresql-primary.mantra-canary-net-1-applications.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox
PGPORT=5432
PGUSER=blockscout
PGDATABASE=blockscout
ECTO_USE_SSL=false
POOL_SIZE=50
POOL_SIZE_API=10
INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true
FIRST_BLOCK=23801
TRACE_FIRST_BLOCK=23801
WITHDRAWALS_FIRST_BLOCK=23801
INDEXER_TX_ACTIONS_REINDEX_FIRST_BLOCK=23801

ETHEREUM_JSONRPC_HTTP_TIMEOUT=120000
ETHEREUM_JSONRPC_TRACE_TIMEOUT=120000
ETHEREUM_JSONRPC_WAIT_PER_TIMEOUT=30s

INDEXER_RECEIPTS_BATCH_SIZE=5
INDEXER_RECEIPTS_CONCURRENCY=3
INDEXER_CATCHUP_BLOCKS_BATCH_SIZE=5
INDEXER_CATCHUP_BLOCKS_CONCURRENCY=3
INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE=5
INDEXER_INTERNAL_TRANSACTIONS_CONCURRENCY=2
INDEXER_COIN_BALANCES_BATCH_SIZE=50
INDEXER_COIN_BALANCES_CONCURRENCY=2
INDEXER_TOKEN_BALANCES_BATCH_SIZE=50
INDEXER_TOKEN_BALANCES_CONCURRENCY=5

INDEXER_MEMORY_LIMIT=6gb