ETHEREUM_JSONRPC_HTTP_URL=http://mantra-canary-net-1-ae2-archive-rpc.mantra-canary-net-1.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox:8545
ETHEREUM_JSONRPC_FALLBACK_HTTP_URL=https://evm.canary.mantrachain.dev
ETHEREUM_JSONRPC_TRACE_URL=http://mantra-canary-net-1-ae2-archive-rpc.mantra-canary-net-1.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox:8545
ETHEREUM_JSONRPC_FALLBACK_TRACE_URL=https://evm.canary.mantrachain.dev
ETHEREUM_JSONRPC_WS_URL=http://mantra-canary-net-1-ae2-archive-rpc.mantra-canary-net-1.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox:8546
ETHEREUM_JSONRPC_FALLBACK_WS_URL=https://evm.canary.mantrachain.dev/ws
NETWORK=CANARY
BLOCKSCOUT_HOST=blockscout.canary.mantrachain.dev
BLOCKSCOUT_PROTOCOL=https
PGHOST=blockscout-canary-postgresql.mantra-canary-net-1-applications.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox
PGPORT=5432
PGUSER=blockscout
PGDATABASE=blockscout
ECTO_USE_SSL=false
FIRST_BLOCK=23801
TRACE_FIRST_BLOCK=1661301
DISPLAY_TOKEN_ICONS=true
SENSITIVE_ENDPOINTS_API_KEY=zyk7DTH1jpn8hnb!wpa
ACCOUNT_ENABLED=true
ACCOUNT_REDIS_URL=redis://blockscout-canary-redis-master.mantra-canary-net-1-applications.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox:6379
ACCOUNT_POOL_SIZE=10
ACCOUNT_AUTH0_DOMAIN=dev-0jb7d5nkxzm67n33.us.auth0.com
ACCOUNT_AUTH0_CLIENT_ID=55mQkU3ASMacoHyv7tVZyYIbBsn69EYy
ACCOUNT_SENDGRID_SENDER=noreply@blockscout.canary.mantrachain.dev
ACCOUNT_SENDGRID_TEMPLATE=d-6c360201e7ef4ed6adf784c1ba766139
ACCOUNT_CLOAK_KEY=WZ2YwYbd0LcvWLFsnfgBf7oLGE2Jqssxvz3AHhL9Bk4=
