NEXT_PUBLIC_APP_HOST=blockscout.canary.mantrachain.dev
NEXT_PUBLIC_NETWORK_NAME=CANARY
NEXT_PUBLIC_NETWORK_ID=7888
NEXT_PUBLIC_API_HOST=blockscout.canary.mantrachain.dev
NEXT_PUBLIC_API_BASE_PATH=
NEXT_PUBLIC_API_SPEC_URL=https://raw.githubusercontent.com/blockscout/blockscout-api-v2-swagger/main/swagger.yaml
NEXT_PUBLIC_NETWORK_ICON=https://raw.githubusercontent.com/cosmos/chain-registry/refs/heads/master/mantrachain/images/OM-Prim-Col.svg
NEXT_PUBLIC_NETWORK_ICON_DARK=https://raw.githubusercontent.com/cosmos/chain-registry/refs/heads/master/mantrachain/images/OM-Darkmatt.svg
NEXT_PUBLIC_NETWORK_LOGO=https://raw.githubusercontent.com/cosmos/chain-registry/refs/heads/master/mantrachain/images/OM-Prim-Col.svg
NEXT_PUBLIC_NETWORK_LOGO_DARK=https://raw.githubusercontent.com/cosmos/chain-registry/refs/heads/master/mantrachain/images/OM-Darkmatt.svg
NEXT_PUBLIC_IS_TESTNET=true
NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=419f16951e5fc4ba28a57059dbf70441
NEXT_PUBLIC_NETWORK_RPC_URL=https://rpc.canary.mantrachain.dev
NEXT_PUBLIC_HOMEPAGE_CHARTS=['daily_txs','coin_price']
NEXT_PUBLIC_IS_ACCOUNT_SUPPORTED=true
NEXT_PUBLIC_RE_CAPTCHA_APP_SITE_KEY=6LfwmBgsAAAAABlQZur1F64irIDZLRkOt5N-zGlq
NEXT_PUBLIC_CONTRACT_INFO_API_HOST=https://contracts-info.services.blockscout.com
NEXT_PUBLIC_ADMIN_SERVICE_API_HOST=https://admin-rs.services.blockscout.com
NEXT_PUBLIC_METADATA_SERVICE_API_HOST=https://metadata.services.blockscout.com