apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: blockscout-canary-mantrachain-dev
  annotations:
    external-dns.ambassador-service: emissary-ingress.emissary
spec:
  hostname: blockscout.canary.mantrachain.dev
  acmeProvider:
    authority: none
  tlsSecret:
    name: asia-east2-std.canary.mantrachain.dev-wildcard-tls-secret
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: blockscout-canary-mantrachain-dev
spec:
  hostname: "blockscout.canary.mantrachain.dev"
  prefix: /
  service: blockscout-stack-canary-frontend-svc:80
  precedence: 0
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: api-blockscout.canary.mantrachain.dev
spec:
  hostname: "blockscout.canary.mantrachain.dev"
  prefix: /api
  rewrite: ""
  service: blockscout-stack-canary-blockscout-svc:80
  allow_upgrade:
    - websocket
  precedence: 1
---
# Backend socket (Phoenix websocket)
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: socket-blockscout.canary.mantrachain.dev
spec:
  hostname: blockscout.canary.mantrachain.dev
  prefix: /socket
  rewrite: /socket
  service: blockscout-stack-canary-blockscout-svc:80
  allow_upgrade:
    - websocket
  precedence: 1
---
# (Optional) public metrics
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: metrics-blockscout.canary.mantrachain.dev
spec:
  hostname: blockscout.canary.mantrachain.dev
  prefix: /public-metrics
  service: blockscout-stack-canary-blockscout-svc:80
  precedence: 1