apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: blockscout-stack-canary-backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: blockscout-stack-canary-blockscout
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: blockscout-stack-canary-frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: blockscout-stack-canary-frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: blockscout-stack-canary-blockscout-indexer
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: blockscout-stack-canary-blockscout-indexer