ETHEREUM_JSONRPC_HTTP_URL=http://nvnm-tempo-devnet-1-rpc-public.nvnm-tempo-devnet-1.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox:8545
ETHEREUM_JSONRPC_FALLBACK_HTTP_URL=https://rpc.nvnm.canary.mantrachain.dev
ETHEREUM_JSONRPC_TRACE_URL=http://nvnm-tempo-devnet-1-rpc-public.nvnm-tempo-devnet-1.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox:8545
ETHEREUM_JSONRPC_FALLBACK_TRACE_URL=https://rpc.nvnm.canary.mantrachain.dev
ETHEREUM_JSONRPC_WS_URL=http://nvnm-tempo-devnet-1-rpc-public.nvnm-tempo-devnet-1.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox:8546
ETHEREUM_JSONRPC_FALLBACK_WS_URL=https://ws.nvnm.canary.mantrachain.dev
NETWORK=NVNM Devnet
BLOCKSCOUT_HOST=blockscout.nvnm.canary.mantrachain.dev
BLOCKSCOUT_PROTOCOL=https
PGHOST=blockscout-nvnm-postgresql.nvnm-tempo-devnet-1-applications.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox
PGPORT=5432
PGUSER=blockscout
PGDATABASE=blockscout
ECTO_USE_SSL=false
