ETHEREUM_JSONRPC_HTTP_URL=http://nvnm-dryrun-1-ae2-v0-sentry-evm.nvnm-dryrun-1.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox:8545
ETHEREUM_JSONRPC_FALLBACK_HTTP_URL=https://evm.nvnm.dryrun.mantrachain.dev
ETHEREUM_JSONRPC_TRACE_URL=http://nvnm-dryrun-1-ae2-v0-sentry-evm.nvnm-dryrun-1.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox:8545
ETHEREUM_JSONRPC_FALLBACK_TRACE_URL=https://evm.nvnm.dryrun.mantrachain.dev
ETHEREUM_JSONRPC_WS_URL=http://nvnm-dryrun-1-ae2-v0-sentry-evm.nvnm-dryrun-1.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox:8546
ETHEREUM_JSONRPC_FALLBACK_WS_URL=https://evm.nvnm.dryrun.mantrachain.dev/ws
NETWORK=NVNM Dryrun
BLOCKSCOUT_HOST=blockscout.nvnm.dryrun.mantrachain.dev
BLOCKSCOUT_PROTOCOL=https
PGHOST=blockscout-nvnm-postgresql.nvnm-dryrun-1-applications.svc.mantra-chain-asia-east2-std.mantra-chain-sandbox.sandbox
PGPORT=5432
PGUSER=blockscout
PGDATABASE=blockscout
ECTO_USE_SSL=false
FIRST_BLOCK=1
POOL_SIZE=25
POOL_SIZE_API=25
