apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: blockscout-stack-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: blockscout-stack-postgres-db-url
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secrets-manager
  target:
    name: blockscout-stack-secrets
    creationPolicy: Owner