apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: blockscout-nvnm-postgres-password-secret
spec:
  data:
    - secretKey: "password"
      remoteRef:
        conversionStrategy: Default
        key: blockscout-nvnm-postgres-password
    - secretKey: "PGPASSWORD"
      remoteRef:
        conversionStrategy: Default
        key: blockscout-nvnm-postgres-password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secrets-manager
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: blockscout-nvnm-postgres-password-secret
