apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: blockscout-canary-secrets
spec:
  data:
    - secretKey: "ACCOUNT_AUTH0_CLIENT_SECRET"
      remoteRef:
        conversionStrategy: Default
        key: blockscout-canary-auth0-client-secret
    - secretKey: "ACCOUNT_PUBLIC_TAGS_AIRTABLE_API_KEY"
      remoteRef:
        conversionStrategy: Default
        key: blockscout-canary-airtable-api-key
    - secretKey: "RE_CAPTCHA_SECRET_KEY"
      remoteRef:
        conversionStrategy: Default
        key: blockscout-canary-recaptcha-secret-key
    - secretKey: "ACCOUNT_SENDGRID_API_KEY"
      remoteRef:
        conversionStrategy: Default
        key: blockscout-canary-sendgrid-api-key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secrets-manager
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: blockscout-canary-secrets
