apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: evm-explorer-dukong-io
  annotations:
    external-dns.ambassador-service: emissary-ingress.emissary
spec:
  hostname: explorer.dukong.io
  acmeProvider:
    authority: none
  tlsSecret:
    name: dukong.io-wildcard-tls-secret
    namespace: emissary
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: evm-explorer-dukong-io
spec:
  hostname: "explorer.dukong.io"
  prefix: /
  service: blockscout-stack-frontend-svc:80
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: api-evm-explorer-dukong-io
  annotations:
    external-dns.ambassador-service: emissary-ingress.emissary
spec:
  hostname: api.explorer.dukong.io
  acmeProvider:
    authority: none
  tlsSecret:
    name: dukong.io-wildcard-tls-secret
    namespace: emissary
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: api-evm-explorer-dukong-io
spec:
  hostname: "api.explorer.dukong.io"
  prefix: /
  service: blockscout-stack-blockscout-svc:80
  allow_upgrade:
  - websocket
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: api-explorer-dukong-io
spec:
  hostname: "explorer.dukong.io"
  prefix: /blockscout
  rewrite: /
  precedence: 1
  service: blockscout-stack-blockscout-svc:80
  allow_upgrade:
  - websocket
