apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: evm-explorer-dukong-io
  annotations:
    external-dns.ambassador-service: emissary-ingress.emissary
spec:
  hostname: explorer.dukong.io
  acmeProvider:
    authority: none
  tlsSecret:
    name: dukong.io-wildcard-tls-secret
    namespace: emissary
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: evm-explorer-dukong-io
spec:
  hostname: "explorer.dukong.io"
  prefix: /
  service: blockscout-stack-frontend-svc:80
  precedence: 0
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: explorer-backend-api
spec:
  hostname: explorer.dukong.io
  prefix: /api
  rewrite: /api
  service: blockscout-stack-blockscout-svc:80
  allow_upgrade:
    - websocket
  precedence: 1
---
# Backend socket (Phoenix websocket)
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: explorer-backend-socket
spec:
  hostname: explorer.dukong.io
  prefix: /socket
  service: blockscout-stack-blockscout-svc:80
  allow_upgrade:
    - websocket
  precedence: 1
---
# (Optional) public metrics
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: explorer-backend-metrics
spec:
  hostname: explorer.dukong.io
  prefix: /public-metrics
  service: blockscout-stack-blockscout-svc:80
  precedence: 1