apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: blockscout-mantrascan-io
  annotations:
    external-dns.ambassador-service: emissary-ingress.emissary
spec:
  hostname: blockscout.mantrascan.io
  acmeProvider:
    authority: none
  tlsSecret:
    name: mantrascan.io-wildcard-tls-secret
    namespace: emissary
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: blockscout-mantrascan-io
spec:
  hostname: "blockscout.mantrascan.io"
  prefix: /
  service: blockscout-stack-frontend-svc:80
  precedence: 0
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: api-blockscout.mantrascan.io
spec:
  hostname: "blockscout.mantrascan.io"
  prefix: /api
  rewrite: /api
  service: blockscout-stack-blockscout-svc:80
  allow_upgrade:
    - websocket
  precedence: 1
---
# Backend socket (Phoenix websocket)
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: socket-blockscout.mantrascan.io
spec:
  hostname: blockscout.mantrascan.io
  prefix: /socket
  service: blockscout-stack-blockscout-svc:80
  allow_upgrade:
    - websocket
  precedence: 1
---
# (Optional) public metrics
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: metrics-blockscout.mantrascan.io
spec:
  hostname: blockscout.mantrascan.io
  prefix: /public-metrics
  service: blockscout-stack-blockscout-svc:80
  precedence: 1